# Manipulate Data with `NDArray`

NDArray - primary tool for data storage and transformation in MXNet.

We’ll start by introducing the `NDArray`, MXNet’s primary tool for storing and transforming data. If you’ve worked with `NumPy` before, you’ll notice that a NDArray is, by design, similar to NumPy’s multi-dimensional array. 

## Getting Started

To get started, let's import the `ndarray` package (`nd` is shortform) from MXNet.

In [1]:
import mxnet as mx
from mxnet import nd

### Create a 2-D Array

Next, let's see how to create a 2-D array (also called a matrix) with values from two sets of numbers: 1, 2, 3 and 4, 5, 6. This might also be referred to as a tuple of a tuple of integers.

In [2]:
# set ctx=mx.gpu(0) to create one on a GPU
a = nd.array(((1,2,3),(5,6,7)), ctx=mx.cpu())
a


[[ 1.  2.  3.]
 [ 5.  6.  7.]]
<NDArray 2x3 @cpu(0)>

### Create a 2-D Array of Ones

We can also create a very simple matrix with the same shape (2 rows by 3 columns), but fill it with 1s.

In [3]:
ones = nd.ones((2,3))
ones


[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>

### Create an Array of Random Values

Often we’ll want to create arrays whose values are sampled randomly. For example, sampling values uniformly between -1 and 1. Here we create the same shape, but with random sampling.

In [4]:
rand_uniform = nd.random.uniform(-1,1,shape=(3,3))
rand_uniform


[[ 0.09762704  0.18568921  0.43037868]
 [ 0.68853152  0.20552671  0.71589124]
 [ 0.08976638  0.69450343 -0.15269041]]
<NDArray 3x3 @cpu(0)>

You can also fill an array of a given shape with a given value, such as `2.0`.
<!-- added to improve multiplication example -->

In [5]:
twos = nd.full((2,3), 2.0)
twos


[[ 2.  2.  2.]
 [ 2.  2.  2.]]
<NDArray 2x3 @cpu(0)>

### Inspect an NDArray's Attributes

As with NumPy, the dimensions of each NDArray are accessible by accessing the `.shape` attribute. We can also query its `size`, which is equal to the product of the components of the shape. In addition, `.dtype` tells the data type of the stored values.

In [6]:
(a.shape, a.size, a.dtype, a.context)

((2, 3), 6, numpy.float32, cpu(0))

## Operations

NDArray supports a large number of standard mathematical operations.

### Element-wise Operations

In [7]:
twos = nd.full((2,3), 2.0)
a * twos


[[  2.   4.   6.]
 [ 10.  12.  14.]]
<NDArray 2x3 @cpu(0)>

In [8]:
twos.exp()


[[ 7.38905621  7.38905621  7.38905621]
 [ 7.38905621  7.38905621  7.38905621]]
<NDArray 2x3 @cpu(0)>

### Matrix Multiplications

And grab a matrix’s transpose to compute a proper matrix-matrix product:

In [9]:
nd.dot(a, a.T)


[[  14.   38.]
 [  38.  110.]]
<NDArray 2x2 @cpu(0)>

## Indexing

#### Read a Particular Element

MXNet NDArrays support slicing in all the ridiculous ways you might imagine accessing your data. Here’s an example of reading a particular element, which returns a 1D array with shape `(1,)`.

In [10]:
a[1,2]


[ 7.]
<NDArray 1 @cpu(0)>

#### Read the Second and Third Columns

In [11]:
a[:,1:3]


[[ 2.  3.]
 [ 6.  7.]]
<NDArray 2x2 @cpu(0)>

#### Use Negative Indices

In [12]:
a[-1]


[ 5.  6.  7.]
<NDArray 3 @cpu(0)>

#### Write to a Specific Element

In [13]:
a[:,1:3] = 2
a


[[ 1.  2.  2.]
 [ 5.  2.  2.]]
<NDArray 2x3 @cpu(0)>

#### Use Multi-dimensional Slicing

In [14]:
a[1:2,0:2] = 4
a


[[ 1.  2.  2.]
 [ 4.  4.  2.]]
<NDArray 2x3 @cpu(0)>

## Converting between MXNet NDArray and NumPy

Converting MXNet NDArrays to and from NumPy is easy. The converted arrays do not share memory.

In [15]:
x = a.asnumpy()
(type(x), x)

(numpy.ndarray, array([[ 1.,  2.,  2.],
        [ 4.,  4.,  2.]], dtype=float32))

In [16]:
nd.array(x);